/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientFrame.java
 *
 * Created on Mar 22, 2010, 4:39:43 PM
 */

package main;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;
import main.daemon.Command;
import main.daemon.CommandListener;
import main.sphinx.SphinxCommandThread;
import main.tts.TextToSpeech;

/**
 *
 * @author Sandro Badame <a href="mailto:s.badame@gmail.com">s.badame&amp;gmail.com</a>
 */
public class ClientFrame extends javax.swing.JFrame implements CommandListener{

    Client client;
    SphinxCommandThread sphinxthread;

    CardLayout layout;
    TestPanel testPanel;
    LeadPanel leadPanel;
    LearnPanel learnPanel;

    String testName = "test";
    String leadName = "lead";
    String learnName = "learn";

    public ClientFrame(){
        this(null);
    }

    /** Creates new form ClientFrame */
    public ClientFrame(Client c) {
        this.client = c;
        client.getDaemon().addListener(this);

        initComponents();

        testPanel = new TestPanel(c);
        leadPanel = new LeadPanel(c);
        learnPanel = new LearnPanel(c);

        layout = (CardLayout) modePanel.getLayout();
        modePanel.add(testPanel, testName);
        modePanel.add(leadPanel,leadName );
        modePanel.add(learnPanel, learnName);
        modePanel.setLayout(layout);
        layout.show(modePanel, testName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        testbutton = new javax.swing.JRadioButton();
        learnbutton = new javax.swing.JRadioButton();
        leadbutton = new javax.swing.JRadioButton();
        modePanel = new javax.swing.JPanel();
        voicerecognition = new javax.swing.JCheckBox();
        tts = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PatherBot");

        infoArea.setColumns(20);
        infoArea.setEditable(false);
        infoArea.setRows(5);
        jScrollPane1.setViewportView(infoArea);

        buttongroup.add(testbutton);
        testbutton.setSelected(true);
        testbutton.setText("Test");
        testbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testbuttonActionPerformed(evt);
            }
        });

        buttongroup.add(learnbutton);
        learnbutton.setText("Learn");
        learnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnbuttonActionPerformed(evt);
            }
        });

        buttongroup.add(leadbutton);
        leadbutton.setText("Lead");
        leadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadbuttonActionPerformed(evt);
            }
        });

        modePanel.setLayout(new java.awt.CardLayout());

        voicerecognition.setText("Use Voice Recognition");
        voicerecognition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voicerecognitionActionPerformed(evt);
            }
        });

        tts.setText("Use Vocal Acknowledgement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(testbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(learnbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leadbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                                .addComponent(voicerecognition))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(493, Short.MAX_VALUE)
                        .addComponent(tts)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testbutton)
                    .addComponent(learnbutton)
                    .addComponent(leadbutton)
                    .addComponent(voicerecognition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testbuttonActionPerformed
        layout.show(modePanel, testName);
    }//GEN-LAST:event_testbuttonActionPerformed

    private void voicerecognitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voicerecognitionActionPerformed
        if (voicerecognition.isSelected()) {
            if (sphinxthread == null) {
                sphinxthread = new SphinxCommandThread(){
                    @Override
                    public void wordDetected(String word){
                         ClientFrame.this.sphinxWordDetected(word);
                    }
                };
                sphinxthread.start();
            }else{
                sphinxthread.resumeListening();
            }
        }else{
            if (sphinxthread != null) {
                sphinxthread.pauseListening();
            }else{
                System.err.println("Sphinx thread is null, but we're turning it off!");
            }
        }
    }//GEN-LAST:event_voicerecognitionActionPerformed

    private void sphinxWordDetected(String word) {
        if (testbutton.isSelected()) {
            testPanel.sphinxWordDetected(word);
        }
    }


    private void learnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnbuttonActionPerformed
        layout.show(modePanel, learnName);
    }//GEN-LAST:event_learnbuttonActionPerformed

    private void leadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leadbuttonActionPerformed
        layout.show(modePanel, leadName);
    }//GEN-LAST:event_leadbuttonActionPerformed

    public void logInfo(String info){
        infoArea.append(info + "\n" );
    }
    
    public void commandSent(final Command c) {
        SwingUtilities.invokeLater(new Runnable(){
           public void run(){
               if (tts.isSelected()) {
                   TextToSpeech.speak(c.toString());
               }
               logInfo(c.toString());
           }
        });
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttongroup;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton leadbutton;
    private javax.swing.JRadioButton learnbutton;
    private javax.swing.JPanel modePanel;
    private javax.swing.JRadioButton testbutton;
    private javax.swing.JCheckBox tts;
    private javax.swing.JCheckBox voicerecognition;
    // End of variables declaration//GEN-END:variables


}
